=== Building Fifengine on Linux

This guide will help you build fife on various flavors of linux.

==== Build Environment

Firstly, we need to setup an IDE and several build tools.

===== IDE

The are several good IDEs available, including:

* http://codeblocks.org[CodeBlocks]
** http://www.codeblocks.org/downloads/26#linux[Downloading CodeBlocks for Linux]
* http://www.kdevelop.org/[KDevelop]
** https://userbase.kde.org/KDevelop/Install#How_to_install_KDevelop[How to install KDevelop?]
* https://code.visualstudio.com/download[Microsoft "Visual Studio Code" Editor]
** https://code.visualstudio.com/download[Download "Visual Studio Code"]

Now, that you have an IDE installed, you need to setup the required build tools.
This includes an compiler of your choice, the build system CMake, the interface generator Swig and Python.

===== Compiler

You can compile fife with `gcc` or `clang`.

===== CMake

Fife uses CMake as build system. The build system generates the build configuration for the project and set the project up for your specific IDE.

https://cmake.org/download/

===== SWIG

Fife uses Swig as interface generator. Fife itself is written in C++, for being able to access the API from Python, we are wrapping it using Swig.

http://www.swig.org/

===== Python (2.7+)

To build the Python extension you need Python. Fife works with Python 2.7+. 

NOTE: We are working on Python 3 support.

==== Dependencies

Fife depends on a multitude of external libraries.

Our next step is to ensure that all dependencies are installed properly, before you try to build fifengine itself.
You have the choice of building the dependencies from source or fetching pre-build, packaged binaries.

We do not provide a pre-packaged software development kit for Linux.

Additionally, you find more detailed information in the dependencies chapter.

===== Building dependencies from source

===== Using packaged dependencies

====== Debian based systems

On debian based systems you can grab all dependencies by installing the following packages: 

[source,bash]
----
apt-get install -y build-essential libalsa-ocaml-dev libsdl2-dev libboost-dev libsdl2-ttf-dev libsdl2-image-dev libvorbis-dev libalut-dev python2.7 python-dev libboost-regex-dev libboost-filesystem-dev libboost-test-dev swig zlib1g-dev libopenal-dev git python-yaml libxcursor1 libxcursor-dev cmake cmake-data libtinyxml-dev
----

====== Gentoo based systems

[source,bash]
----
emerge --ask --verbose --noreplace libvorbis libogg media-libs/openal boost libsdl2 sdl2-image sdl2-ttf git pyyaml dev-lang/swig dev-libs/tinyxml dev-util/cmake
----

====== Fedora based systems

[source,bash]
----
dnf install git python python-devel gcc gcc-c++ SDL2 SDL2-static SDL2-devel SDL2_ttf SDL2_ttf-devel SDL2_image SDL2_image-devel boost boost-devel libvorbis libvorbis-devel libogg libogg-devel openal-soft openal-soft-devel zlib zlib-devel mesa-libGL mesa-libGL-devel mesa-libGLU mesa-libGLU-devel swig libXcursor libXcursor-devel alsa-lib alsa-lib-devel python-alsa PyYAML allegro5 cmake tinyxml-devel libpng libpng-devel
----

====== Arch Linux based systems

[source,bash]
----
pacman -S sdl2 boost sdl2_ttf sdl2_image libvorbis libogg openal swig python2 zlib libgl libpng tinyxml python2-pillow cmake
----

**NOTE** that you will also need to install http://fifengine.github.com/fifechan/[fifechan] from source, until it's available as a debian package.

==== Building Fifengine

Finally, we can compile Fifengine.

To build Fife, you'll of course need the Fife source code. 
You can download a Fife source code package or fetch the latest source using git.

Please switch into the `<fife>` source directory.

To build fife with python2 support only do:

Then type: `mkdir _build; cd _build; cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr..`.

To build fife with python2 support and with c/c++ lib and header files do:

Then type: `mkdir _build; cd _build; cmake -Dbuild-library=ON -DCMAKE_INSTALL_PREFIX:PATH=/usr..`.

after that do make && sudo make install
