== Contributing

Interested in fife and want to help out? Do you see something that needs improving? 
Better yet, do you have a solution to one of our https://github.com/fifengine/fifengine/issues[open issues]? 

You can support the project in all sorts of areas and we would graciously accept any contributions you have to offer!
Please don't hesitate, if you've got an awesome idea to throw into FIFE.

The best part about contributing to an open source project is you get the satisfaction of improving a project, 
not to mention full recognition for your work! It might help out on that next job application!

=== Help wanted...

This is an open source project and developers are contributing on their own time. 
For this reason we are constantly looking for help.

[NOTE] 
.We are looking for:
====
* Engine developers - All skill levels in C++ and Python
* Web designers - Our website needs an overhaul
* Packagers - We want to improve or cross-platform build automation
* Artists - They are always welcome to contribute some art where it's needed
* Documentors - We want to improve our manuals and API docs
====

.**Engine developers**

We are in great need for all skill levels of developers to help with our C++ and Python extensions.
There is work in just about any field you could imagine, from tool development, to OpenGL eye candy,
to ear popping sound effects, to demo game development. You name it, we need it. Are you new to
coding but want to learn? Are you an experienced coder looking for a project to fill that void in
your life? This is the project for you!

.**Web designers**

Currently our website is lacking a certain POW. It needs to be re-done in the worst way. We are
completely open to your ideas as far as the backend goes. There is a template to start from here.
You could either make some templates for our forums and blog or throw the whole thing out and
surprise us with something else! It's gotta look amazing to attract as much attention as possible!

.**Packagers**

There is a bunch of work that needs to be done here. Our Windows installer needs work, our
development kit needs updating, release packaging needs to be automated, the list is endless really.
Currently we package every release by hand and this a tedious task so any help in this department
would be great!

.**Artists**

What project doesn't need an artist or two? If you have some artistic skills and are looking for a
project, look no further! We have several demos that would benefit from some new art (tilesets, gui
art, icons, etc etc), not to mention our website!

.**Documentors**

As they say, good documentation makes a project. This is one department, where it's difficult to
find people to volunteer their time to help out. Any time you can spend documenting fife or helping
with tutorials would definitely help make fife even better!

=== Workflow

Here's the most direct way to get your work merged into the project:

* Fork the project.
* Clone down your fork ( `git clone git://github.com/<username>/fifengine.git` ).
* Create a topic branch to contain your change ( `git checkout -b my_awesome_feature` ).
* Hack away.
* If necessary, rebase your commits into logical chunks, without errors.
* Push the branch up ( `git push origin my_awesome_feature` ).
* Create a pull request against fifengine/fifengine and describe what your change
  does and the why you think it should be merged.

IMPORTANT: Please follow the [[C++ Coding Standards|coding-standards]] or [[Python Coding Standards|Python-coding-standards]] when modifying code.

=== Gotchas

* Try to keep your patch(es) based from the latest commit on fifengine/fifengine.
  The easier it is to apply your work, the less work the maintainers have to do,
  which is always a good thing.
* Please don't tag your GitHub issue with [fix], [feature], etc. The maintainers
  actively read the issues and will label it once they come across it.

=== Finally...

Thanks for helping us! We look forward to any contributions you make to help improve FIFE!  

=== Working with Git

include::chapter03-working-with-git.adoc[]