=== Building Fifengine on Linux

This guide will help you build fife on various flavors of linux.

==== Build Environment

Firstly, we need to setup an IDE and several build tools.

===== IDE

The are several good IDEs available, including:

* http://codeblocks.org[CodeBlocks]
** http://www.codeblocks.org/downloads/26#linux[Downloading CodeBlocks for Linux]
* http://www.kdevelop.org/[KDevelop]
** https://userbase.kde.org/KDevelop/Install#How_to_install_KDevelop[How to install KDevelop?]
* https://code.visualstudio.com/download[Microsoft "Visual Studio Code" Editor]

Now, that you have an IDE installed, you need to setup the required build tools.
This includes an compiler of your choice, the build system CMake, the interface generator Swig and Python.

===== Compiler

You can compile fife with `gcc` or `clang`.

NOTE: We don't ship a C/C++ compiler in our Windows SDK. Instructions on how to set up a compiler and build system for C++ development on Windows can be found [here](https://userbase.kde.org/KDevelop4/Manual/WindowsSetup).

===== CMake

Fife uses CMake as build system. The build system generates the build configuration for the project and set the project up for your specific IDE.

https://cmake.org/download/

===== SWIG

Fife uses Swig as interface generator. Fife itself is written in C++, for being able to access the API from Python, we are wrapping it using Swig.

http://www.swig.org/

===== Python

To build the Python extension you need Python. Fife works with Python 3.4+

==== Dependencies

Fife depends on a multitude of external libraries.

Our next step is to ensure that all dependencies are installed properly, before you try to build fifengine itself.
You have the choice of building the dependencies from source or fetching pre-build, packaged binaries.

We do not provide a pre-packaged software development kit for Linux.

Additionally, you find more detailed information in the dependencies chapter.

===== Building dependencies from source

NOTE: We are working on building the dependencies on the fly. For now we simply use pre-build packages.

===== Using packaged dependencies

====== Debian based systems

On debian based systems you can grab all dependencies by installing the following packages:

Python 3:

[source,bash]
----
apt-get install -y build-essential libalsa-ocaml-dev libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev libvorbis-dev libalut-dev python3 python3-dev swig zlib1g-dev libopenal-dev git python3-yaml libxcursor1 libxcursor-dev cmake cmake-data libtinyxml2-dev libpng-dev libglew-dev
----

====== Gentoo based systems

Python 3:

[source,bash]
----
emerge --ask --verbose --noreplace libvorbis libogg media-libs/openal libsdl2 sdl2-image sdl2-ttf git pyyaml dev-lang/swig dev-libs/tinyxml2 dev-util/cmake media-libs/glew dev-lang/python3 dev-python/future
----

====== Fedora based systems

Python 3:

[source,bash]
----
dnf install git python3 gcc gcc-c++ SDL2 SDL2-static SDL2-devel SDL2_ttf SDL2_ttf-devel SDL2_image SDL2_image-devel libvorbis libvorbis-devel libogg libogg-devel openal-soft openal-soft-devel zlib zlib-devel mesa-libGL mesa-libGL-devel mesa-libGLU mesa-libGLU-devel swig libXcursor libXcursor-devel alsa-lib alsa-lib-devel python-alsa python3-PyYAML cmake tinyxml2-devel libpng libpng-devel fifechan fifechan-devel fifechan-opengl fifechan-opengl-devel fifechan-sdl fifechan-sdl-devel glew glew-devel
----

====== Arch Linux based systems

Python 3:

[source,bash]
----
pacman -S sdl2 sdl2_ttf sdl2_image libvorbis libogg openal swig python zlib libgl libpng tinyxml2 python-pillow python-future cmake glew
----

**NOTE** that you will also need to install http://fifengine.github.com/fifechan/[fifechan] from source, until it's available as a package for your distro. Fifechan is in the following distros: Fedora

==== Building Fifechan

Fifechan is a C++ GUI library that is required as an optional dependency for FIFE.
You need to build it from source before building FIFE.

===== Install System Dependencies

Fifechan requires the following dependencies to be installed on your system:

[source,bash]
----
apt-get install -y \
  build-essential \
  cmake \
  ninja-build \
  freetype \
  libsdl2-dev \
  libsdl2-image-dev \
  libsdl2-mixer-dev \
  libsdl2-ttf-dev \
  libglew-dev \
  libxcursor-dev \
  libx11-dev \
  libxext-dev
----

For testing (optional):

[source,bash]
----
apt-get install -y catch2
----

===== Clone and Build

[source,bash]
----
git clone https://github.com/fifengine/fifechan.git && cd fifechan
----

Create a build directory and configure with CMake using a preset or manual configuration:

[source,bash]
----
mkdir -p _build && cd _build
cmake --preset gcc14-x64-linux-rel
cmake --build --preset gcc14-x64-linux-rel
----

Or manually with CMake:

[source,bash]
----
mkdir -p _build && cd _build
cmake -G Ninja -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release ..
cmake --build .
sudo cmake --install .
----

===== Build with Clang

[source,bash]
----
mkdir -p _build && cd _build
cmake -G Ninja -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ ..
cmake --build .
sudo cmake --install .
----

==== Building Fifengine

Finally, we can compile Fifengine.

To build Fife, you'll of course need the Fife source code.
You can download a Fife source code package or fetch the latest source using git.

[source,bash]
----
git clone https://github.com/fifengine/fifengine.git && cd fifengine
----

If you have only an old version of cmake (2.X) then please do this:

[source,bash]
----
mkdir ../_build; cd ../_build/; cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr ../fifengine/
instand of: mkdir _build; cd _build; cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr ..
----

To build fife with Python support only do:

[source,bash]
----
With "-DPYTHON_EXECUTABLE=/PATH/TO/PYTHONEXECUTABLE" you can change the Python Version what you want to use. If it is not the System defualt Python Version.
----

[source,bash]
----
mkdir _build; cd _build; cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr ..
----

To build it with Python support only do (with Clang instand of GCC Compiler):

[source,bash]
----
mkdir _build; cd _build; cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ ..
----

To build fife with Python support and with c/c++ lib and header files do:

[source,bash]
----
mkdir _build; cd _build; cmake -Dbuild-library=ON -DCMAKE_INSTALL_PREFIX:PATH=/usr ..
----

To build fife with Python support and with c/c++ lib and header files do (with Clang instand of GCC Compiler):

[source,bash]
----
mkdir _build; cd _build; cmake -Dbuild-library=ON -DCMAKE_INSTALL_PREFIX:PATH=/usr -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ ..
----

after that you can build the project using make and then install it:

[source,bash]
----
make && sudo make install
----
