=== Building Fifengine on Mac

==== Build Environment

Firstly, we need to setup an IDE and several build tools.

===== IDE

The are several good IDEs available, including:

* http://developer.apple.com/tools/xcode/[XCode]
** http://www.codeblocks.org/downloads/26#windows[Downloading CodeBlocks for Windows]
* https://code.visualstudio.com/download[Microsoft "Visual Studio Code"]
** https://code.visualstudio.com/download[Download "Visual Studio Code"]

===== Compiler

TODO

===== CMake

TODO

===== SWIG

TODO

===== Python (2.7+)

TODO

==== Dependencies

Fife depends on a multitude of external libraries.

Our next step is to ensure that all dependencies are installed properly.
We do this by either compiling and installing them manually or by fetching and installing pre-compiled binaries.

We do not provide a pre-packaged software development kit for Mac.

Additionally, you find more detailed information in the dependencies chapter.

===== Building dependencies from source

NOTE: We are working on building the dependencies on the fly. For now we simply use pre-build packages.

===== Using packaged dependencies

brew update && brew install swig sdl2 sdl2_image sdl2_ttf freetype openal-soft tinyxml glew libvorbis

==== Building Fifengine

Finally, we can compile Fifengine.
