== Contributing

So, you've got an awesome idea to throw into FIFE or you want to contribute by fixing an https://github.com/fifengine/fifengine/issues[Issue].

IMPORTANT: Please follow the [[C++ Coding Standards|coding-standards]] or [[Python Coding Standards|Python-coding-standards]] when modifying code.

=== Workflow

Here's the most direct way to get your work merged into the project:

* Fork the project.
* Clone down your fork ( `git clone git://github.com/<username>/fifengine.git` ).
* Create a topic branch to contain your change ( `git checkout -b my_awesome_feature` ).
* Hack away.
* If necessary, rebase your commits into logical chunks, without errors.
* Push the branch up ( `git push origin my_awesome_feature` ).
* Create a pull request against fifengine/fifengine and describe what your change
  does and the why you think it should be merged.

=== Gotchas

* Try to keep your patch(es) based from the latest commit on fifengine/fifengine.
  The easier it is to apply your work, the less work the maintainers have to do,
  which is always a good thing.
* Please don't tag your GitHub issue with [fix], [feature], etc. The maintainers
  actively read the issues and will label it once they come across it.

=== Finally...

Thanks for helping us! We look forward to any contributions you make to help improve FIFE!  