=== Building Fifengine on Windows

==== Build Environment

Firstly, we need to setup an IDE and several build tools.

===== IDE

The are several good IDEs available, including:

* https://www.visualstudio.com/[Microsoft Visual Studio]
** https://www.visualstudio.com/downloads/[Download Visual Studio Community]
** https://go.microsoft.com/fwlink/?LinkId=691978&clcid=0x409[Download Visual Studio Community - Webinstaller (english)]
** https://go.microsoft.com/fwlink/?LinkId=691978&clcid=0x407[Download Visual Studio Community - Webinstaller (german)]
* https://code.visualstudio.com/download[Microsoft "Visual Studio Code" Editor]
** https://code.visualstudio.com/download[Download "Visual Studio Code"]
* http://codeblocks.org/[CodeBlocks]
** http://www.codeblocks.org/downloads/26#windows[Downloading CodeBlocks for Windows]

===== Compiler

You need `msvc` or `gcc`.

In case you installed MS Visual Studio, then the MSVC compiler is already installed.

===== CMake

Fife uses CMake as build system. The build system generates the build configuration for the project and set the project up for your specific IDE.

https://cmake.org/download/

===== SWIG

Fife uses Swig as interface generator. Fife itself is written in C++, for being able to access the API from Python, we are wrapping it using Swig.

http://www.swig.org/

===== Python

To build the Python extension you need Python. Fife works with Python 3.4+

* http://python.org/[Python]
** https://www.python.org/downloads/windows/[Python Downloads for Windows]
** https://www.python.org/ftp/python/3.5.2/python-3.5.2.exe[Download Python 3.5.2 (exe)]

==== Dependencies

Fifengine depends on several external libraries.

This is the https://fifengine.github.io/fifengine-docs/developer-manual/en/#_fifengine_dependencies[detailed list].

Our next step is to ensure that all dependencies are installed properly, before you try to build fifengine itself.
You have the choice of building the dependencies from source or fetching pre-build, packaged binaries.

===== Using packaged dependencies

The pre-build binaries are build on-the-fly, when building Fifengine on Appveyor.
You find MSVC 14 builds here: https://ci.appveyor.com/project/LinuxDonald/fifengine

These builds are also included in our pre-packaged Windows development kit,
the https://ci.appveyor.com/project/LinuxDonald/fife-windows-sdk/branch/master/artifacts[Fife-SDK].

The default install location is `fifengine-dependencies` next to your `fifengine` source folder.
When you're using an alternative location, please set the library and include dirs for the dependencies accordingly.

===== Building dependencies from source

You can build the dependencies for Windows using MSVC.

The CMake config file for the dependencies is `fifengine\dependencies\CMakeLists.txt`.
It includes the individual scripts for fetching and building dependencies.
They are located in the main CMake scripts folder: `fifengine\cmake\get-*.cmake`.

Let's configure the dependencies project and then build all dependencies:

[source,bash]
----
cmake dependencies -G "Visual Studio 14" -B../fifengine-dependencies/build
cmake --build ../fifengine-dependencies/build --target ALL_BUILD --config Release
----

You'll now find the dependencies the `fifengine-dependencies` folder:

[source,bash]
----
dir ..\fifengine-dependencies
dir ..\fifengine-dependencies\downloads
dir ..\fifengine-dependencies\includes /s
----

==== Building Fifechan

Fifechan is a C++ GUI library that is required as an optional dependency for FIFE.
You need to build it from source before building FIFE.

===== Install Dependencies

Download and install the following dependencies:

* https://cmake.org/download/[CMake] - version 3.25 or higher
* https://www.libsdl.org/download-2.0.php[SDL2] - Development libraries
* https://www.libsdl.org/projects/SDL_image/[SDL2_image]
* https://www.libsdl.org/projects/SDL_mixer/[SDL2_mixer]
* https://www.libsdl.org/projects/SDL_ttf/[SDL2_ttf]
* https://www.freetype.org/download.html[FreeType]
* https://github.com/catchorg/Catch2/releases[catch2] (optional, for tests)

===== Clone and Build

Open the Developer Command Prompt for Visual Studio, then:

[source,bash]
----
git clone https://github.com/fifengine/fifechan.git
cd fifechan
mkdir _build
cd _build
cmake -G "Visual Studio 17 2022" -A x64 -DCMAKE_INSTALL_PREFIX=C:\fifechan ..
cmake --build . --config Release
cmake --install . --config Release
----

For Debug builds, replace `Release` with `Debug`.

===== Using CMake Presets

Fifechan includes CMake presets. To use them:

[source,bash]
----
cmake --preset vc17-x64-windows-rel
cmake --build --preset vc17-x64-windows-rel
cmake --install --preset vc17-x64-windows-rel
----

==== Building Fifengine

If you have Python 3 installed you can choose the Version with the command:

[source,bash]
----
With "-DPYTHON_EXECUTABLE=/PATH/TO/PYTHONEXECUTABLE" you can change the Python Version what you want to use. If it is not the System defualt Python Version.
----

Finally, we can compile Fifengine.

To build Fife, you'll of course need the Fife source code.
You can download a Fife source code package or fetch the latest source using git.

[source,bash]
----
git clone https://github.com/fifengine/fifengine.git && cd fifengine
----

Configure and build using CMake:

[source,bash]
----
mkdir _build
cd _build
cmake -G "Visual Studio 17 2022" -A x64 ..
cmake --build . --config Release
----

To specify a custom Python executable, add the `-DPYTHON_EXECUTABLE` option:

[source,bash]
----
cmake -G "Visual Studio 17 2022" -A x64 -DPYTHON_EXECUTABLE=C:\Python311\python.exe ..
cmake --build . --config Release
----

To build with the C/C++ library and header files:

[source,bash]
----
cmake -G "Visual Studio 17 2022" -A x64 -Dbuild-library=ON ..
cmake --build . --config Release
----

For Debug builds, replace `Release` with `Debug`.
