=== Building Fifengine on Windows

==== Build Environment

Firstly, we need to setup an IDE and several build tools.

===== IDE

The are several good IDEs available, including:

* https://www.visualstudio.com/[Microsoft Visual Studio]
** https://www.visualstudio.com/downloads/[Download Visual Studio Community]
** https://go.microsoft.com/fwlink/?LinkId=691978&clcid=0x409[Download Visual Studio Community - Webinstaller (english)]
** https://go.microsoft.com/fwlink/?LinkId=691978&clcid=0x407[Download Visual Studio Community - Webinstaller (german)]
* https://code.visualstudio.com/download[Microsoft "Visual Studio Code" Editor]
** https://code.visualstudio.com/download[Download "Visual Studio Code"]
* http://codeblocks.org/[CodeBlocks]
** http://www.codeblocks.org/downloads/26#windows[Downloading CodeBlocks for Windows]

===== Compiler

You need `msvc` or `gcc` or `mingw-gcc`. 

In case you installed MS Visual Studio, then the MSVC compiler is already installed.

[IMPORTANT] 
.gcc and mingw-gcc toolchain support is not ready, yet
====
In case you want to build using `gcc`, we suggest using one of the following toolchains:

* http://tdm-gcc.tdragon.net/[tdragon's TDM-GCC MinGW]
** This compiler and toolchain is also included in our Fife-SDK for MinGW.
* http://mingw-w64.org/[MinGW-W64]
====

===== CMake

Fife uses CMake as build system. The build system generates the build configuration for the project and set the project up for your specific IDE.

https://cmake.org/download/

===== SWIG

Fife uses Swig as interface generator. Fife itself is written in C++, for being able to access the API from Python, we are wrapping it using Swig.

http://www.swig.org/

===== Python

To build the Python extension you need Python. Fife works with Python 2.7 and Python 3.4+

* http://python.org/[Python]
** https://www.python.org/downloads/windows/[Python Downloads for Windows]
** https://www.python.org/ftp/python/2.7.12/python-2.7.12.msi[Download Python 2.7.12 (msi)]
** https://www.python.org/ftp/python/3.5.2/python-3.5.2.exe[Download Python 3.5.2 (exe)]

==== Dependencies

Fifengine depends on several external libraries.

This is the https://fifengine.github.io/fifengine-docs/developer-manual/en/#_fifengine_dependencies[detailed list].

Our next step is to ensure that all dependencies are installed properly, before you try to build fifengine itself.
You have the choice of building the dependencies from source or fetching pre-build, packaged binaries.

===== Using packaged dependencies

The pre-build binaries are build on-the-fly, when building Fifengine on Appveyor.
You find MSVC 14 builds here: https://ci.appveyor.com/project/LinuxDonald/fifengine

NOTE: We are working on building the dependencies on the fly using the MinGW toolchain.

These builds are also included in our pre-packaged Windows development kit, 
the https://ci.appveyor.com/project/LinuxDonald/fife-windows-sdk/branch/master/artifacts[Fife-SDK].

The default install location is `fifengine-dependencies` next to your `fifengine` source folder.
When you're using an alternative location, please set the library and include dirs for the dependencies accordingly.

===== Building dependencies from source

You can build the dependencies for Windows using MSVC.

The CMake config file for the dependencies is `fifengine\dependencies\CMakeLists.txt`.
It includes the individual scripts for fetching and building dependencies. 
They are located in the main CMake scripts folder: `fifengine\cmake\get-*.cmake`.

Let's configure the dependencies project and then build all dependencies:

[source,bash]
----
cmake dependencies -G "Visual Studio 14" -B../fifengine-dependencies/build
cmake --build ../fifengine-dependencies/build --target ALL_BUILD --config Release 
----

You'll now find the dependencies the `fifengine-dependencies` folder:

[source,bash]
----
dir ..\fifengine-dependencies
dir ..\fifengine-dependencies\downloads
dir ..\fifengine-dependencies\includes /s
----

==== Building Fifengine

If you have Python 2 and Python 3 installed you can choose the Version with the comamnd:

[source,bash]
----
With "-DPYTHON_EXECUTABLE=/PATH/TO/PYTHONEXECUTABLE" you can change the Python Version what you want to use. If it is not the System defualt Python Version.
----

Finally, we can compile Fifengine.
