=== CMake configuration options

We provide several configuration flags, which allow configuring the fifengine build.

[horizontal]

`cmake ..\fifengine`:: We are building in a seperate build folder: the `fifengine-build` folder, project source is one up, then down into fifengine. This is called out-of-source-tree building. 

`-G %GENERATOR%`:: You need to specifiy the requested GENERATOR IDE. This is either `"Visual Studio 14"` or `"Mingw makefiles"`. Others values are possible. See CMake generators for more.

`-DCMAKE_PREFIX_PATH="c:/project/fifengine-dependencies/includes"`:: where the includes are

`-DCMAKE_BUILD_TYPE=%CONFIGURATION%`:: Release or Debug

`-DCMAKE_INSTALL_PREFIX="c:/project/fife-install"`:: the installation folder

`-DBOOST_INCLUDEDIR="c:/project\fifengine-dependencies\includes\include\boost"`:: helpers to find boost

`-DBOOST_LIBRARYDIR="c:/project\fifengine-dependencies\includes\lib\boost"`:: helpers to find boost

`-DPYTHON_INCLUDE_DIR="C:/Python27/include"`:: helpers to find Python

`-DPYTHON_LIBRARY="C:/Python27/libs/python27.lib"`:: helpers to find Python

`-DSWIG_DIR=<path-to>swig`:: helpers to find Swig

`-DSWIG_EXECUTABLE=<path-to>\swig\swig.exe`:: helpers to find Swig

`-Dbuild-library=ON`:: This build flags enables building the shared library (ON). When disabled (OFF), then only the Python extension is build.

`-DBUILD_SHARED_LIBS=ON`:: This build flag controls, whether to build a shared (ON) or static library (OFF).